version: 2.1
orbs:
  docker: circleci/docker@1.0.0
workflows:
  deploy:
    jobs:
      - docker/build:
          image: maijahaka/devopswithdocker-part-3
          tag: 'registry.heroku.com/devopswithdocker-part-3'