version: 2.1
orbs:
  docker: circleci/docker@1.0.0
jobs:
  heroku-publish:
    machine:
      enabled: true
    steps:
        - docker/publish:
          image: maijahaka/devopswithdocker-part-3
          tag: 'latest'
        - run:
            name: Tag image for Heroku deployment
            command: docker tag devopswithdocker-part-3 devopswithdocker-part-3:herokutest
workflows:
  deploy:
    jobs:
      - heroku-publish