version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: sudo curl https://cli-assets.heroku.com/install.sh | sh
      - run: |    
            echo "$HEROKU_API_KEY" | docker login --username $HEROKU_LOGIN --password-stdin registry.heroku.com
      - run: docker build -t $HEROKU_APP .
      - run: heroku container:login
      - run: heroku container:push web
      - run: heroku container:release web
workflows:
  build-and-deploy:
    jobs:
      - build