version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      #- run: |
          echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_LOGIN --password-stdin
      #- run: docker build -t $HEROKU_APP:testtag .
      #- run: docker images
      - run: heroku --version
workflows:
  build-and-deploy:
    jobs:
      - build