version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
          echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_LOGIN --password-stdin
workflows:
  build-and-deploy:
    jobs:
      - build