version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      #- run: |
          #echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_LOGIN --password-stdin
      #- run: docker build -t $HEROKU_APP:testtag .
      #- run: docker images
      - run: |
          echo "$HEROKU_PASSWORD" | docker login --username $HEROKU_LOGIN --password-stdin registry.heroku.com

workflows:
  build-and-deploy:
    jobs:
      - build