version: 2.1
orbs:
  docker: circleci/docker@1.0.0
jobs:
  heroku-publish:
    machine:
      enabled: true
    steps:
        - run:
            name: Tag image for Heroku deployment
            command: docker tag devopswithdocker-part-3:latest devopswithdocker-part-3:herokutest
workflows:
  deploy:
    jobs:
      - docker/publish:
          image: maijahaka/devopswithdocker-part-3
          tag: 'latest'
      - heroku-publish:
          requires:
            - docker/publish