version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
          echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_LOGIN --password-stdin
      - run: |    
          echo "$HEROKU_API_KEY" | docker login --username $HEROKU_LOGIN --password-stdin registry.heroku.com
      - run: docker build -t $HEROKU_APP .
      - run: docker tag $HEROKU_APP $HEROKU_APP:testtag

workflows:
  build-and-deploy:
    jobs:
      - build